### ISSUE TITLE
How to handle scenario where out-of-tree driver depends on in-tree driver(s)

### ISSUE THREAD

**Issue by hershpa** [intel/intel-data-center-gpu-driver-for-openshift#49]
### **Summary**
The Intel GPU i915 driver has a large dependency tree. It depends on several in-tree drivers present in /lib/modules/(KERNELRELEASE)/. In the scenario where an out of tree driver depends on in-tree driver(s), the user needs to copy in-tree drivers into /opt/lib/modules/(KERNELRELEASE)/ rather than leveraging the in-tree drivers directly on the host. This is because everything is done in /opt including modprobe -d /opt (done explicitly by KMM) as well as depmod -b /opt (done in dockerfile).

### Goal 
The goal is to determine if we can avoid copying in-tree drivers. Only out of tree drivers should be a part of the driver container image.

### Possible Solution
This is a complex problem where a solution may not feasible. If we continue to use /opt to avoid tainting the default /lib directory, it would require copying in-tree drivers from the host by using a modules.dep file (this file would contain dependency list and would be generated after placing the out of tree drivers modules in /lib). From a KMM perspective, it would receive a driver container with exclusively out of tree drivers and then use the supplied modules.dep to copy over the necessary in-tree drivers to successfully load the out of tree driver. This solution could involve host mounting and sym links.

**Comment by hershpa** [comment]
Hi @qbarrand, we would love to have your perspective here. We can also discuss this in upcoming KMM community meeting.

**Comment by hershpa** [comment]
Any update on this one @qbarrand, we would like to resolve this known issue in our upcoming release if possible, thanks!

**Comment by qbarrand** [comment]
Hey @hershpa, it looks like support for this in the v2 branch will onlky land in version 2.0.1 or 2.1. I do not have a reliable timeline as of today but I will keep you posted here.

**Comment by hershpa** [comment]
Thanks @qbarrand!
